### ISSUE TITLE
should check if comment already starts with a space

### ISSUE THREAD

**Issue by millermedeiros** [briandipalma/esformatter-spaced-lined-comment#1]
some example inputs:

``` js
// this comment already starts with a single space
// ---

// some chart
//   |---+
//       | ------ bar
```

you probably just need to check if first char of `token.value` is a space; unsure what to do if first char is a `Tab`

**Comment by feross** [comment]
+1 Please don't add a space if the comment already starts with a space.

**Comment by Flet** [comment]
+1 +PR #2 :sunglasses:

**Comment by briandipalma** [comment]
I am so sorry that I haven't replied yet! I have stopped emails from GitHub as I was watching way to many repos but that means even my own repos don't notify me. Very, very sorry about this!

I will take a look at these requests PR now, sorry again!

**Comment by briandipalma** [comment]
OK I've published version 2 with the merged changes, it should be OK now.

**Comment by Flet** [comment]
Great, thanks!
